keys:
  - &ruby 5cff335b7c2710a4d1586eae143ae77e0efdfe1c
  - &gateway 51ef34681bcddc37351da26e02faf6f5e6407234
  - &opal-entrypoint 4c0dea3daac864e94969b7e459237d1765c4940e
creation_rules:
  - path_regex: secrets/gateway\.yaml$
    key_groups:
      - pgp:
        - *ruby
        - *gateway
  - path_regex: secrets/opal-entrypoint\.yaml$
    key_groups:
      - pgp:
        - *ruby
        - *opal-entrypoint
